theme: jekyll-theme-hacker
title: Project Insomnia's Temporary Home Page
description: Project Insomnia is a project based group that we started in Early 2020. This groups purpose is to not only provide education to our members, but also give them the experience they need to exceed out in a career they love. We also like working with other groups and becoming interactive with the community. 
